import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { headers } from 'next/headers';
import { type ReactNode } from 'react';
import { cookieToInitialState } from 'wagmi';
import { getConfig } from '../../wagmi';
import { Providers } from '../providers';
import Header from '@/components/core/header';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Crypto All Stars',
  description: 'Generated by create-wagmi',
};

export default async function RootLayout(props: {
  children: ReactNode;
  params: { locale: string };
}) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get('cookie')
  );

  if (!routing.locales.includes(props.params.locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={props.params.locale}>
      <head>
        <link rel="icon" href="favicon.ico" />
      </head>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Providers initialState={initialState}>
            <Header />
            {props.children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
